Sorry: TabError: inconsistent use of tabs and spaces in indentation (trajectory_from_csv.py, line 62)
